# Linter Options
options:
  merge-default-rules: false
  formatter: compact

# File Options
files:
  include: 'app/**/*.scss'

# Rule Configuration
  #  0 === ignore
  #  1 === warn
  #  2 === error
rules:
#  attribute-quotes: true
  bem-depth: 2
  border-zero:
    - 1
    - convention: none
  brace-style:
    - 1
    -
      style: 1tbs
      allow-single-line: true
  class-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: "hyphenatedbem"
  clean-import-paths: 1
  empty-args: 1
  empty-line-between-blocks: 0
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting : 0
  function-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: "hyphenatedbem"
  hex-length: 1
  hex-notation: 1
  id-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: "hyphenatedlowercase"
  indentation:
    - 1
    - size: 4
  leading-zero:
    - 1
    - include: true
  mixin-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: "hyphenatedbem"
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 4 # Block + modifier + element + modifier
  no-attribute-selectors: 0
  no-color-keywords: 1
  no-color-hex: 0
  no-color-literals: 1
  no-combinators: 0
  no-css-comments: 1
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 1
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors:
    - 0
    - whitelist: []
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements:
    - 0
    -
      allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: true
  no-trailing-whitespace: 1
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  no-warn: 1
  one-declaration-per-line: 1
  placeholder-in-extend: 1
  placeholder-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: "hyphenatedbem"
  property-sort-order: 0
  property-units:
    - 0
    -
      global: []
      per-property: {}
  pseudo-element: 0
  quotes:
    - 1
    - style: single
  shorthand-values:
    - 1
    - allowed-shorthands: [1, 2, 3]
  single-line-per-selector: 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon: 1
  space-after-comma: 1
  space-around-operator:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace: 1
  space-before-colon:
    - 1
    - include: false
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon:
    - 1
    - include: true
  url-quotes: 1
  variable-for-property:
    - 1
    - properties: []
  variable-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: "hyphenatedbem"
  zero-unit:
    - 1
    - include: false
